name: Deployment Pipeline

env:
  COMMITS_WITHOUT_SKIP_AND_PUSHES: ${{ !contains(join(github.event.commits.*.message, ' '), '#skip') && github.event_name == 'push' }}

on: 
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - name: Say hello
        run: echo "Hello pipeline!"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build  
      - if: ${{ env.COMMITS_WITHOUT_SKIP_AND_PUSHES == 'true' }}
        uses: superfly/flyctl-actions/setup-flyctl@master
      - if: ${{ env.COMMITS_WITHOUT_SKIP_AND_PUSHES == 'true' }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  tag_release:
    runs-on: ubuntu-latest
    needs: [simple_deployment_pipeline] # Ensures that the deployment pipeline is complete before bumping the version
    steps:
      - if: ${{ env.COMMITS_WITHOUT_SKIP_AND_PUSHES == 'true' }}
        uses: actions/checkout@v4
      - if: ${{ env.COMMITS_WITHOUT_SKIP_AND_PUSHES == 'true' }} # Ensures the version is only bumped on a merge or push
        name: Bump version and push tag
        id: version-bump
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: 'patch'
      - if: ${{env.COMMITS_WITHOUT_SKIP_AND_PUSHES == 'true' && success()}}
        env:
          NEW_TAG: ${{steps.version-bump.outputs.new_tag}}
          OLD_TAG: ${{steps.version-bump.outputs.old_tag}}
          PART: ${{steps.version-bump.outputs.part}}
          REPO_NAME: ${{github.repository}}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          username: hookerbot
          color: '#031a85'
          text: Version Update!
          description: A new version of Pokedex has been deployed!
          details: 'A new version is available for ${{env.REPO_NAME}}! ${{env.PART}} release from ${{env.OLD_TAG}} --> ${{env.NEW_TAG}}'
          webhookUrl: ${{secrets.DISCORD_WEBHOOK}}